
spring:
  session:
    store-type: none
  application:
    name: sdk4-cloud-gateway
  zipkin:
      base-url: http://localhost:9012

server:
  port: 9020

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9011/eureka/

zuul:
  routes:
    baidu:
      path: /bd/**
      url: https://www.baidu.com/
    s:
      path: /base/**
      serviceId: sdk4-cloud-base
