
spring:
  session:
    store-type: none
  application:
    name: sdk4-cloud-demo-client
  zipkin:
    base-url: http://localhost:9012

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9011/eureka/
